In [2]:
import numpy as np

# Creating an array using numpy

#Creating a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
# 2D Array
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape :", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size (Number of elements :)", arr.size)
print("Data type :", arr.dtype)
print("Item size (in bytes) :", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of Dimensions:  2
Size (Number of elements :) 6
Data type : int64
Item size (in bytes) : 8


In [ ]:
# Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element Wise Addition
print("Addition :", arr1+arr2)

#Element Wise Substraction
print("Substraction :", arr1-arr2)

#Element Wise Multiplication
print("Multiplication :", arr1*arr2)

#Element Wise Division
print("Division :", arr1/arr2)

Addition : [11 22 33 44 55]
Substraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [25]:
# Universal Function

arr=np.array([2,3,4,5,6])

# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
# Array Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array :\n", arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
arr[0]

array([1, 2, 3, 4])

In [30]:
print(arr[0][0])

1


In [34]:
print(arr[1:,2:])


[[ 7  8]
 [11 12]]


In [35]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [36]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [37]:
# Modifying Array Elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [38]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [43]:
#Statistical Conceptsn - Normalization
# Mean, Median & Standard Deviation

data= np.array([1,2,3,4,5])

#Mean and Standard Deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized Data:", normalized_data)



Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
data1=np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean1=np.mean(data1)
print("Mean: ",mean1)

#Median

median=np.median(data1)
print("Median :", median)

#Standard Deviation
std_dev1=np.std(data1)
print("Standard Deviation: ",std_dev1)

#Variance
variance=np.var(data1)
print("Variance :", variance)

Mean:  5.5
Median : 5.5
Standard Deviation:  2.8722813232690143
Variance : 8.25


In [50]:
#Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data>5]) 

print(data[data<=8])

data[(data>5) & (data<=8)]

[ 6  7  8  9 10]
[1 2 3 4 5 6 7 8]


array([6, 7, 8])